list<-read.delim("/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/list_2.txt",sep="\t")
head(list)
#abc1<-read.delim("/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/cancer_data/zp_1000_big.txt")
#abc2<-read.delim("/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/cancer_data/zp_2000_big.txt")
#abc2<-merge(abc1,abc2,x.by="ref",y.by="ref")
#write.table(abc2,"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_1_2.txt",sep="\t",row.names=F)
#abc3<-read.delim("/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/cancer_data/zp_3000_big.txt")
#abc3<-merge(abc2,abc3,x.by="ref",y.by="ref")
#write.table(abc3,"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_2_3.txt",sep="\t",row.names=F)
#abc4<-read.delim("/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/cancer_data/zp_4000_big.txt")
#abc4<-merge(abc3,abc4,x.by="ref",y.by="ref")
#write.table(abc4,"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_3_4.txt",sep="\t",row.names=F)
#abc5<-read.delim("/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/cancer_data_part2/zp_2_1000_big.txt")
#abc5<-merge(abc4,abc5,x.by="ref",y.by="ref")
#write.table(abc5,"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_4_5.txt",sep="\t",row.names=F)
#abc6<-read.delim("/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/cancer_data_part2/zp_2_2000_big.txt")
#abc6<-merge(abc5,abc6,x.by="ref",y.by="ref")
#write.table(abc6,"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_5_6.txt",sep="\t",row.names=F)
abc10<-read.delim("/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_5_6.txt")
#abc7<-read.delim("/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/cancer_data_part2/zp_2_3000_big.txt")
#abc7<-merge(abc6,abc7,x.by="ref",y.by="ref")
#write.table(abc7,"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_6_7.txt",sep="\t",row.names=F)
#abc8<-read.delim("/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/cancer_data_part2/zp_2_4000_big.txt")
#abc8<-merge(abc7,abc8,x.by="ref",y.by="ref")
#write.table(abc8,"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_7_8.txt",sep="\t",row.names=F)
#abc9<-read.delim("/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/cancer_data_part2/zp_2_5000_big.txt")
#abc9<-merge(abc8,abc9,x.by="ref",y.by="ref")
#write.table(abc9,"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_8_9.txt",sep="\t",row.names=F)
#abc10<-read.delim("/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/cancer_data_part2/zp_2_6000_big.txt")
#abc10<-merge(abc9,abc10,x.by="ref",y.by="ref")
#write.table(abc10,"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_9_10.txt",sep="\t",row.names=F)

list[,15] <-sapply(list[,15],function(x) gsub("-",".",x,perl = TRUE))
g<-colnames(abc10)
g<-g[-1]
k<-c(1:length(g))

#for(i in c(1:length(g))){
#k[i]<-as.character(z[which(as.character(z[,15])==g[i]),4])
#}
write.table(abc10[c(1:50000),],"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_10_1_6.txt",sep="\t",row.names=F)
write.table(abc10[c(50001:100000),],"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_10_2_6.txt",sep="\t",row.names=F)
write.table(abc10[c(100001:150000),],"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_10_3_6.txt",sep="\t",row.names=F)
write.table(abc10[c(150001:200000),],"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_10_4_6.txt",sep="\t",row.names=F)
write.table(abc10[c(200001:250000),],"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_10_5_6.txt",sep="\t",row.names=F)
write.table(abc10[c(250001:300000),],"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_10_6_6.txt",sep="\t",row.names=F)
write.table(abc10[c(300001:350000),],"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_10_7_6.txt",sep="\t",row.names=F)
write.table(abc10[c(350001:400000),],"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_10_8_6.txt",sep="\t",row.names=F)
write.table(abc10[c(400001:450000),],"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_10_9_6.txt",sep="\t",row.names=F)
write.table(abc10[c(450001:length(abc10[,1])),],"/mnt/ilustre/users/sanger-dev/sg-users/zhangpeng/fighting/data_all/data_10_9_6.txt",sep="\t",row.names=F)



